from __future__ import annotations

from app.domain.enums import CategoryDimension as D
from app.domain.seeds._core import CategorySeed

GENRE_SEEDS: tuple[CategorySeed, ...] = (
    CategorySeed(D.GENRE, "Cinematic", "cinematic"),
    CategorySeed(D.GENRE, "Ambient", "ambient"),
    CategorySeed(D.GENRE, "Electronic", "electronic"),
    CategorySeed(D.GENRE, "Pop", "pop"),
    CategorySeed(D.GENRE, "Rock", "rock"),
    CategorySeed(D.GENRE, "Alternative Rock", "alternative-rock"),
    CategorySeed(D.GENRE, "Indie Rock", "indie-rock"),
    CategorySeed(D.GENRE, "Hip-Hop", "hip-hop"),
    CategorySeed(D.GENRE, "R&B", "rnb"),
    CategorySeed(D.GENRE, "Soul", "soul"),
    CategorySeed(D.GENRE, "Funk", "funk"),
    CategorySeed(D.GENRE, "Jazz", "jazz"),
    CategorySeed(D.GENRE, "Blues", "blues"),
    CategorySeed(D.GENRE, "Classical", "classical"),
    CategorySeed(D.GENRE, "Orchestral", "orchestral"),
    CategorySeed(D.GENRE, "Chamber Music", "chamber-music"),
    CategorySeed(D.GENRE, "Folk", "folk"),
    CategorySeed(D.GENRE, "Country", "country"),
    CategorySeed(D.GENRE, "Americana", "americana"),
    CategorySeed(D.GENRE, "Bluegrass", "bluegrass"),
    CategorySeed(D.GENRE, "Metal", "metal"),
    CategorySeed(D.GENRE, "Heavy Metal", "heavy-metal"),
    CategorySeed(D.GENRE, "Death Metal", "death-metal"),
    CategorySeed(D.GENRE, "Black Metal", "black-metal"),
    CategorySeed(D.GENRE, "Punk", "punk"),
    CategorySeed(D.GENRE, "Post-Punk", "post-punk"),
    CategorySeed(D.GENRE, "Hardcore", "hardcore"),
    CategorySeed(D.GENRE, "Disco", "disco"),
    CategorySeed(D.GENRE, "House", "house"),
    CategorySeed(D.GENRE, "Deep House", "deep-house"),
    CategorySeed(D.GENRE, "Techno", "techno"),
    CategorySeed(D.GENRE, "Trance", "trance"),
    CategorySeed(D.GENRE, "Drum and Bass", "drum-and-bass"),
    CategorySeed(D.GENRE, "Dubstep", "dubstep"),
    CategorySeed(D.GENRE, "Trap", "trap"),
    CategorySeed(D.GENRE, "Lo-Fi", "lo-fi"),
    CategorySeed(D.GENRE, "Synthwave", "synthwave"),
    CategorySeed(D.GENRE, "Vaporwave", "vaporwave"),
    CategorySeed(D.GENRE, "Industrial", "industrial"),
    CategorySeed(D.GENRE, "New Age", "new-age"),
    CategorySeed(D.GENRE, "World", "world"),
    CategorySeed(D.GENRE, "Latin", "latin"),
    CategorySeed(D.GENRE, "Reggae", "reggae"),
    CategorySeed(D.GENRE, "Dub", "dub"),
    CategorySeed(D.GENRE, "Ska", "ska"),
    CategorySeed(D.GENRE, "Gospel", "gospel"),
    CategorySeed(D.GENRE, "Musical Theatre", "musical-theatre"),
    CategorySeed(D.GENRE, "Soundtrack", "soundtrack"),
    CategorySeed(D.GENRE, "Game Score", "game-score"),
    CategorySeed(D.GENRE, "Trailer Music", "trailer-music"),
    CategorySeed(D.GENRE, "Experimental", "experimental"),
    CategorySeed(D.GENRE, "Noise", "noise"),
    CategorySeed(D.GENRE, "Shoegaze", "shoegaze"),
    CategorySeed(D.GENRE, "Dream Pop", "dream-pop"),
    CategorySeed(D.GENRE, "Trip Hop", "trip-hop"),
    CategorySeed(D.GENRE, "Grunge", "grunge"),
    CategorySeed(D.GENRE, "Emo", "emo"),
    CategorySeed(D.GENRE, "K-Pop", "k-pop"),
    CategorySeed(D.GENRE, "Afrobeats", "afrobeats"),
    CategorySeed(D.GENRE, "Bossa Nova", "bossa-nova"),
    CategorySeed(D.GENRE, "Flamenco", "flamenco"),
    CategorySeed(D.GENRE, "Celtic", "celtic"),
    CategorySeed(D.GENRE, "Middle Eastern", "middle-eastern"),
    CategorySeed(D.GENRE, "Indian Classical", "indian-classical"),
)
