from __future__ import annotations

from app.domain.enums import CategoryDimension as D
from app.domain.seeds._core import CategorySeed

INSTRUMENT_SEEDS: tuple[CategorySeed, ...] = (
    CategorySeed(D.INSTRUMENT, "Piano", "piano"),
    CategorySeed(D.INSTRUMENT, "Grand Piano", "grand-piano"),
    CategorySeed(D.INSTRUMENT, "Electric Piano", "electric-piano"),
    CategorySeed(D.INSTRUMENT, "Rhodes", "rhodes"),
    CategorySeed(D.INSTRUMENT, "Organ", "organ"),
    CategorySeed(D.INSTRUMENT, "Hammond Organ", "hammond-organ"),
    CategorySeed(D.INSTRUMENT, "Acoustic Guitar", "acoustic-guitar"),
    CategorySeed(D.INSTRUMENT, "Electric Guitar", "electric-guitar"),
    CategorySeed(D.INSTRUMENT, "Classical Guitar", "classical-guitar"),
    CategorySeed(D.INSTRUMENT, "Bass Guitar", "bass-guitar"),
    CategorySeed(D.INSTRUMENT, "Upright Bass", "upright-bass"),
    CategorySeed(D.INSTRUMENT, "Synth Bass", "synth-bass"),
    CategorySeed(D.INSTRUMENT, "Drums", "drums"),
    CategorySeed(D.INSTRUMENT, "Drum Machine", "drum-machine"),
    CategorySeed(D.INSTRUMENT, "Percussion", "percussion"),
    CategorySeed(D.INSTRUMENT, "Congas", "congas"),
    CategorySeed(D.INSTRUMENT, "Bongos", "bongos"),
    CategorySeed(D.INSTRUMENT, "Timpani", "timpani"),
    CategorySeed(D.INSTRUMENT, "Cymbals", "cymbals"),
    CategorySeed(D.INSTRUMENT, "Strings", "strings"),
    CategorySeed(D.INSTRUMENT, "Violin", "violin"),
    CategorySeed(D.INSTRUMENT, "Viola", "viola"),
    CategorySeed(D.INSTRUMENT, "Cello", "cello"),
    CategorySeed(D.INSTRUMENT, "Double Bass", "double-bass"),
    CategorySeed(D.INSTRUMENT, "String Section", "string-section"),
    CategorySeed(D.INSTRUMENT, "Brass", "brass"),
    CategorySeed(D.INSTRUMENT, "Trumpet", "trumpet"),
    CategorySeed(D.INSTRUMENT, "Trombone", "trombone"),
    CategorySeed(D.INSTRUMENT, "French Horn", "french-horn"),
    CategorySeed(D.INSTRUMENT, "Tuba", "tuba"),
    CategorySeed(D.INSTRUMENT, "Woodwinds", "woodwinds"),
    CategorySeed(D.INSTRUMENT, "Flute", "flute"),
    CategorySeed(D.INSTRUMENT, "Clarinet", "clarinet"),
    CategorySeed(D.INSTRUMENT, "Oboe", "oboe"),
    CategorySeed(D.INSTRUMENT, "Bassoon", "bassoon"),
    CategorySeed(D.INSTRUMENT, "Saxophone", "saxophone"),
    CategorySeed(D.INSTRUMENT, "Synthesizer", "synthesizer"),
    CategorySeed(D.INSTRUMENT, "Analog Synth", "analog-synth"),
    CategorySeed(D.INSTRUMENT, "Pad Synth", "pad-synth"),
    CategorySeed(D.INSTRUMENT, "Lead Synth", "lead-synth"),
    CategorySeed(D.INSTRUMENT, "Harpsichord", "harpsichord"),
    CategorySeed(D.INSTRUMENT, "Harp", "harp"),
    CategorySeed(D.INSTRUMENT, "Mallet", "mallet"),
    CategorySeed(D.INSTRUMENT, "Marimba", "marimba"),
    CategorySeed(D.INSTRUMENT, "Vibraphone", "vibraphone"),
    CategorySeed(D.INSTRUMENT, "Glockenspiel", "glockenspiel"),
    CategorySeed(D.INSTRUMENT, "Bell", "bell"),
    CategorySeed(D.INSTRUMENT, "Choir", "choir"),
    CategorySeed(D.INSTRUMENT, "Vocal Sample", "vocal-sample"),
    CategorySeed(D.INSTRUMENT, "Sampler", "sampler"),
    CategorySeed(D.INSTRUMENT, "Theremin", "theremin"),
    CategorySeed(D.INSTRUMENT, "Accordion", "accordion"),
    CategorySeed(D.INSTRUMENT, "Banjo", "banjo"),
    CategorySeed(D.INSTRUMENT, "Mandolin", "mandolin"),
    CategorySeed(D.INSTRUMENT, "Ukulele", "ukulele"),
    CategorySeed(D.INSTRUMENT, "Harmonica", "harmonica"),
    CategorySeed(D.INSTRUMENT, "Pipe Organ", "pipe-organ"),
    CategorySeed(D.INSTRUMENT, "Taiko", "taiko"),
    CategorySeed(D.INSTRUMENT, "Sitar", "sitar"),
    CategorySeed(D.INSTRUMENT, "Tabla", "tabla"),
    CategorySeed(D.INSTRUMENT, "Erhu", "erhu"),
    CategorySeed(D.INSTRUMENT, "Koto", "koto"),
    CategorySeed(D.INSTRUMENT, "Steel Drums", "steel-drums"),
)
