from __future__ import annotations

from app.domain.enums import CategoryDimension as D
from app.domain.seeds._core import CategorySeed

MOOD_SEEDS: tuple[CategorySeed, ...] = (
    CategorySeed(D.MOOD, "Haunting", "haunting"),
    CategorySeed(D.MOOD, "Melancholic", "melancholic"),
    CategorySeed(D.MOOD, "Somber", "somber"),
    CategorySeed(D.MOOD, "Joyful", "joyful"),
    CategorySeed(D.MOOD, "Euphoric", "euphoric"),
    CategorySeed(D.MOOD, "Playful", "playful"),
    CategorySeed(D.MOOD, "Tense", "tense"),
    CategorySeed(D.MOOD, "Suspenseful", "suspenseful"),
    CategorySeed(D.MOOD, "Anxious", "anxious"),
    CategorySeed(D.MOOD, "Romantic", "romantic"),
    CategorySeed(D.MOOD, "Sensual", "sensual"),
    CategorySeed(D.MOOD, "Mystical", "mystical"),
    CategorySeed(D.MOOD, "Ethereal", "ethereal"),
    CategorySeed(D.MOOD, "Aggressive", "aggressive"),
    CategorySeed(D.MOOD, "Fierce", "fierce"),
    CategorySeed(D.MOOD, "Peaceful", "peaceful"),
    CategorySeed(D.MOOD, "Serene", "serene"),
    CategorySeed(D.MOOD, "Nostalgic", "nostalgic"),
    CategorySeed(D.MOOD, "Bittersweet", "bittersweet"),
    CategorySeed(D.MOOD, "Epic", "epic"),
    CategorySeed(D.MOOD, "Heroic", "heroic"),
    CategorySeed(D.MOOD, "Triumphant", "triumphant"),
    CategorySeed(D.MOOD, "Dreamy", "dreamy"),
    CategorySeed(D.MOOD, "Dark", "dark"),
    CategorySeed(D.MOOD, "Ominous", "ominous"),
    CategorySeed(D.MOOD, "Hopeful", "hopeful"),
    CategorySeed(D.MOOD, "Uplifting", "uplifting"),
    CategorySeed(D.MOOD, "Lonely", "lonely"),
    CategorySeed(D.MOOD, "Introspective", "introspective"),
    CategorySeed(D.MOOD, "Mysterious", "mysterious"),
    CategorySeed(D.MOOD, "Whimsical", "whimsical"),
    CategorySeed(D.MOOD, "Cinematic Tension", "cinematic-tension"),
    CategorySeed(D.MOOD, "Gritty", "gritty"),
    CategorySeed(D.MOOD, "Warm", "warm"),
    CategorySeed(D.MOOD, "Cold", "cold"),
    CategorySeed(D.MOOD, "Dramatic", "dramatic"),
    CategorySeed(D.MOOD, "Reflective", "reflective"),
    CategorySeed(D.MOOD, "Energetic", "energetic"),
    CategorySeed(D.MOOD, "Chill", "chill"),
    CategorySeed(D.MOOD, "Meditative", "meditative"),
)
