from __future__ import annotations

from app.domain.enums import CategoryDimension as D
from app.domain.seeds._core import CategorySeed

PRODUCTION_SEEDS: tuple[CategorySeed, ...] = (
    CategorySeed(D.PRODUCTION, "Dark Reverb", "dark-reverb"),
    CategorySeed(D.PRODUCTION, "Hall Reverb", "hall-reverb"),
    CategorySeed(D.PRODUCTION, "Plate Reverb", "plate-reverb"),
    CategorySeed(D.PRODUCTION, "Spring Reverb", "spring-reverb"),
    CategorySeed(D.PRODUCTION, "Room Reverb", "room-reverb"),
    CategorySeed(D.PRODUCTION, "Shimmer Reverb", "shimmer-reverb"),
    CategorySeed(D.PRODUCTION, "Tape Delay", "tape-delay"),
    CategorySeed(D.PRODUCTION, "Slapback Delay", "slapback-delay"),
    CategorySeed(D.PRODUCTION, "Ping-Pong Delay", "ping-pong-delay"),
    CategorySeed(D.PRODUCTION, "Tape Saturation", "tape-saturation"),
    CategorySeed(D.PRODUCTION, "Tube Warmth", "tube-warmth"),
    CategorySeed(D.PRODUCTION, "Lo-Fi Degradation", "lo-fi-degradation"),
    CategorySeed(D.PRODUCTION, "Bit Crushing", "bit-crushing"),
    CategorySeed(D.PRODUCTION, "Sidechain Compression", "sidechain-compression"),
    CategorySeed(D.PRODUCTION, "Parallel Compression", "parallel-compression"),
    CategorySeed(D.PRODUCTION, "Multiband Compression", "multiband-compression"),
    CategorySeed(D.PRODUCTION, "Gated Reverb", "gated-reverb"),
    CategorySeed(D.PRODUCTION, "Reverse Reverb", "reverse-reverb"),
    CategorySeed(D.PRODUCTION, "Reverse Audio", "reverse-audio"),
    CategorySeed(D.PRODUCTION, "Filter Sweep", "filter-sweep"),
    CategorySeed(D.PRODUCTION, "Low-Pass Filter", "low-pass-filter"),
    CategorySeed(D.PRODUCTION, "High-Pass Filter", "high-pass-filter"),
    CategorySeed(D.PRODUCTION, "Auto-Filter", "auto-filter"),
    CategorySeed(D.PRODUCTION, "Chorus Effect", "chorus-effect"),
    CategorySeed(D.PRODUCTION, "Flanger", "flanger"),
    CategorySeed(D.PRODUCTION, "Phaser", "phaser"),
    CategorySeed(D.PRODUCTION, "Tremolo Effect", "tremolo-effect"),
    CategorySeed(D.PRODUCTION, "Distortion", "distortion"),
    CategorySeed(D.PRODUCTION, "Overdrive", "overdrive"),
    CategorySeed(D.PRODUCTION, "Fuzz", "fuzz"),
    CategorySeed(D.PRODUCTION, "Vinyl Crackle", "vinyl-crackle"),
    CategorySeed(D.PRODUCTION, "Tape Hiss", "tape-hiss"),
    CategorySeed(D.PRODUCTION, "Room Ambience", "room-ambience"),
    CategorySeed(D.PRODUCTION, "Convolution Reverb", "convolution-reverb"),
    CategorySeed(D.PRODUCTION, "Stereo Widening", "stereo-widening"),
    CategorySeed(D.PRODUCTION, "Mid-Side Processing", "mid-side-processing"),
    CategorySeed(D.PRODUCTION, "Parallel Saturation", "parallel-saturation"),
    CategorySeed(D.PRODUCTION, "Sub-Bass Enhancement", "sub-bass-enhancement"),
    CategorySeed(D.PRODUCTION, "Transient Shaping", "transient-shaping"),
)
