from __future__ import annotations

from app.domain.enums import CategoryDimension as D
from app.domain.seeds._core import CategorySeed

TECHNIQUE_SEEDS: tuple[CategorySeed, ...] = (
    CategorySeed(D.TECHNIQUE, "Ghost Notes", "ghost-notes"),
    CategorySeed(D.TECHNIQUE, "Portamento", "portamento"),
    CategorySeed(D.TECHNIQUE, "Glissando", "glissando"),
    CategorySeed(D.TECHNIQUE, "Arpeggio", "arpeggio"),
    CategorySeed(D.TECHNIQUE, "Staccato", "staccato"),
    CategorySeed(D.TECHNIQUE, "Legato", "legato"),
    CategorySeed(D.TECHNIQUE, "Tremolo", "tremolo"),
    CategorySeed(D.TECHNIQUE, "Vibrato", "vibrato"),
    CategorySeed(D.TECHNIQUE, "Trill", "trill"),
    CategorySeed(D.TECHNIQUE, "Pizzicato", "pizzicato"),
    CategorySeed(D.TECHNIQUE, "Bowing", "bowing"),
    CategorySeed(D.TECHNIQUE, "Strumming", "strumming"),
    CategorySeed(D.TECHNIQUE, "Fingerpicking", "fingerpicking"),
    CategorySeed(D.TECHNIQUE, "Palm Muting", "palm-muting"),
    CategorySeed(D.TECHNIQUE, "Bending", "bending"),
    CategorySeed(D.TECHNIQUE, "Hammer-On", "hammer-on"),
    CategorySeed(D.TECHNIQUE, "Pull-Off", "pull-off"),
    CategorySeed(D.TECHNIQUE, "Slide Guitar", "slide-guitar"),
    CategorySeed(D.TECHNIQUE, "Tapping", "tapping"),
    CategorySeed(D.TECHNIQUE, "Sweep Picking", "sweep-picking"),
    CategorySeed(D.TECHNIQUE, "Double Stops", "double-stops"),
    CategorySeed(D.TECHNIQUE, "Counterpoint", "counterpoint"),
    CategorySeed(D.TECHNIQUE, "Canon", "canon"),
    CategorySeed(D.TECHNIQUE, "Ostinato", "ostinato"),
    CategorySeed(D.TECHNIQUE, "Pedal Point", "pedal-point"),
    CategorySeed(D.TECHNIQUE, "Call and Response", "call-and-response"),
    CategorySeed(D.TECHNIQUE, "Improvisation", "improvisation"),
    CategorySeed(D.TECHNIQUE, "Syncopation", "syncopation"),
    CategorySeed(D.TECHNIQUE, "Polyrhythm", "polyrhythm"),
    CategorySeed(D.TECHNIQUE, "Rubato", "rubato"),
    CategorySeed(D.TECHNIQUE, "Crescendo", "crescendo"),
    CategorySeed(D.TECHNIQUE, "Diminuendo", "diminuendo"),
    CategorySeed(D.TECHNIQUE, "Staccato Strings", "staccato-strings"),
    CategorySeed(D.TECHNIQUE, "Tremolo Strings", "tremolo-strings"),
    CategorySeed(D.TECHNIQUE, "Muted Trumpet", "muted-trumpet"),
    CategorySeed(D.TECHNIQUE, "Flutter Tongue", "flutter-tongue"),
    CategorySeed(D.TECHNIQUE, "Col Legno", "col-legno"),
    CategorySeed(D.TECHNIQUE, "Harmonics", "harmonics"),
    CategorySeed(D.TECHNIQUE, "Prepared Piano", "prepared-piano"),
)
