from __future__ import annotations

from app.domain.enums import CategoryDimension as D
from app.domain.seeds._core import CategorySeed

VOCAL_SEEDS: tuple[CategorySeed, ...] = (
    # Register & timbre
    CategorySeed(D.VOCALS, "Intimate Male", "intimate-male", "Close, soft male vocal delivery"),
    CategorySeed(D.VOCALS, "Intimate Female", "intimate-female", "Close, soft female vocal delivery"),
    CategorySeed(D.VOCALS, "Powerful Male", "powerful-male", "Strong, projected male vocal"),
    CategorySeed(D.VOCALS, "Powerful Female", "powerful-female", "Strong, projected female vocal"),
    CategorySeed(D.VOCALS, "Androgynous Voice", "androgynous-voice", "Gender-neutral vocal timbre"),
    CategorySeed(D.VOCALS, "Baritone", "baritone", "Low male register"),
    CategorySeed(D.VOCALS, "Tenor", "tenor", "High male register"),
    CategorySeed(D.VOCALS, "Bass Voice", "bass-voice", "Lowest male register"),
    CategorySeed(D.VOCALS, "Alto", "alto", "Low female register"),
    CategorySeed(D.VOCALS, "Mezzo-Soprano", "mezzo-soprano", "Middle female register"),
    CategorySeed(D.VOCALS, "Soprano", "soprano", "High female register"),
    CategorySeed(D.VOCALS, "Contralto", "contralto", "Lowest female register"),
    CategorySeed(D.VOCALS, "Child Voice", "child-voice", "Youthful, pre-teen vocal character"),
    CategorySeed(D.VOCALS, "Teen Voice", "teen-voice", "Adolescent vocal character"),
    CategorySeed(D.VOCALS, "Elder Voice", "elder-voice", "Aged, weathered vocal character"),
    # Technique & style
    CategorySeed(D.VOCALS, "Belting", "belting", "High-energy chest-dominant singing"),
    CategorySeed(D.VOCALS, "Whisper", "whisper", "Soft, breathy near-whisper delivery"),
    CategorySeed(D.VOCALS, "Falsetto", "falsetto", "Light upper-register male singing"),
    CategorySeed(D.VOCALS, "Head Voice", "head-voice", "Light, resonant upper register"),
    CategorySeed(D.VOCALS, "Chest Voice", "chest-voice", "Full, resonant lower register"),
    CategorySeed(D.VOCALS, "Mixed Voice", "mixed-voice", "Blended chest and head resonance"),
    CategorySeed(D.VOCALS, "Rapping", "rapping", "Rhythmic spoken-word delivery"),
    CategorySeed(D.VOCALS, "Spoken Word", "spoken-word", "Non-melodic speech performance"),
    CategorySeed(D.VOCALS, "Half-Spoken", "half-spoken", "Speech-song hybrid delivery"),
    CategorySeed(D.VOCALS, "Scat Singing", "scat-singing", "Improvised jazz syllable vocals"),
    CategorySeed(D.VOCALS, "Yodeling", "yodeling", "Rapid register switching"),
    CategorySeed(D.VOCALS, "Growl", "growl", "Low, guttural vocal texture"),
    CategorySeed(D.VOCALS, "Fry Scream", "fry-scream", "Extreme low-register scream"),
    CategorySeed(D.VOCALS, "Clean Vocals", "clean-vocals", "Unprocessed melodic singing"),
    CategorySeed(D.VOCALS, "Operatic", "operatic", "Classical operatic technique"),
    CategorySeed(D.VOCALS, "Jazz Vocals", "jazz-vocals", "Swing, scat, and jazz phrasing"),
    CategorySeed(D.VOCALS, "Soul Vocals", "soul-vocals", "Expressive R&B and soul delivery"),
    CategorySeed(D.VOCALS, "Gospel Vocals", "gospel-vocals", "Church-rooted powerful delivery"),
    CategorySeed(D.VOCALS, "Pop Vocals", "pop-vocals", "Contemporary pop singing style"),
    CategorySeed(D.VOCALS, "Rock Vocals", "rock-vocals", "Edgy rock delivery"),
    CategorySeed(D.VOCALS, "Metal Vocals", "metal-vocals", "Aggressive metal singing or screaming"),
    CategorySeed(D.VOCALS, "R&B Vocals", "rnb-vocals", "Smooth rhythm and blues delivery"),
    CategorySeed(D.VOCALS, "Country Vocals", "country-vocals", "Twang and narrative country style"),
    CategorySeed(D.VOCALS, "Folk Vocals", "folk-vocals", "Acoustic storytelling vocal style"),
    CategorySeed(D.VOCALS, "Choral", "choral", "Classical choir-style singing"),
    CategorySeed(D.VOCALS, "Ensemble Vocals", "ensemble-vocals", "Multiple voices as one texture"),
    CategorySeed(D.VOCALS, "A Cappella", "a-cappella", "Unaccompanied vocal performance"),
    CategorySeed(D.VOCALS, "Barbershop", "barbershop", "Four-part close harmony style"),
    CategorySeed(D.VOCALS, "Musical Theatre", "musical-theatre", "Stage musical vocal style"),
    CategorySeed(D.VOCALS, "Beatboxing", "beatboxing", "Vocal percussion performance"),
    # Phrasing & delivery
    CategorySeed(D.VOCALS, "Legato Vocal", "legato-vocal", "Smooth, connected vocal lines"),
    CategorySeed(D.VOCALS, "Staccato Vocal", "staccato-vocal", "Short, detached vocal phrases"),
    CategorySeed(D.VOCALS, "Melismatic", "melismatic", "Many notes per syllable"),
    CategorySeed(D.VOCALS, "Talk-Singing", "talk-singing", "Conversational melodic delivery"),
    CategorySeed(D.VOCALS, "Call and Response", "call-and-response", "Lead phrase answered by group"),
    CategorySeed(D.VOCALS, "Ad-Libs", "ad-libs", "Improvised vocal fills and exclamations"),
    CategorySeed(D.VOCALS, "Harmonies", "harmonies", "Supporting harmonic vocal lines"),
    CategorySeed(D.VOCALS, "Counter-Melody", "counter-melody", "Secondary melodic vocal line"),
    CategorySeed(D.VOCALS, "Unison Vocals", "unison-vocals", "Multiple voices on same pitch"),
    CategorySeed(D.VOCALS, "Duet", "duet", "Two-voice lead performance"),
    CategorySeed(D.VOCALS, "Choir Backing", "choir-backing", "Choir supporting lead vocal"),
    CategorySeed(D.VOCALS, "Lead Vocal", "lead-vocal", "Primary foreground vocal"),
    CategorySeed(D.VOCALS, "Backing Vocals", "backing-vocals", "Supporting background vocals"),
    CategorySeed(D.VOCALS, "Gang Vocals", "gang-vocals", "Group shout or chant vocals"),
    CategorySeed(D.VOCALS, "Crowd Vocals", "crowd-vocals", "Large-group vocal texture"),
    # Character & tone
    CategorySeed(D.VOCALS, "Breathy", "breathy", "Airy, breath-forward tone"),
    CategorySeed(D.VOCALS, "Nasal", "nasal", "Forward, nasal resonance"),
    CategorySeed(D.VOCALS, "Warm Tone", "warm-tone", "Rich, rounded vocal timbre"),
    CategorySeed(D.VOCALS, "Bright Tone", "bright-tone", "Forward, present upper harmonics"),
    CategorySeed(D.VOCALS, "Dark Tone", "dark-tone", "Deep, subdued vocal color"),
    CategorySeed(D.VOCALS, "Raw", "raw", "Unpolished, emotionally exposed delivery"),
    CategorySeed(D.VOCALS, "Polished", "polished", "Studio-refined vocal performance"),
    CategorySeed(D.VOCALS, "Gritty", "gritty", "Rough, textured vocal edge"),
    CategorySeed(D.VOCALS, "Smooth", "smooth", "Even, controlled vocal flow"),
    CategorySeed(D.VOCALS, "Aggressive Delivery", "aggressive-delivery", "Forceful, confrontational vocal"),
    CategorySeed(D.VOCALS, "Tender Delivery", "tender-delivery", "Gentle, caring vocal expression"),
    CategorySeed(D.VOCALS, "Vulnerable", "vulnerable", "Fragile, emotionally open delivery"),
    CategorySeed(D.VOCALS, "Confident", "confident", "Assured, commanding vocal presence"),
    # Production character
    CategorySeed(D.VOCALS, "Dry Vocal", "dry-vocal", "Minimal effects on vocal"),
    CategorySeed(D.VOCALS, "Reverb-Heavy Vocal", "reverb-heavy-vocal", "Large-space vocal reverb"),
    CategorySeed(D.VOCALS, "Double-Tracked Vocals", "double-tracked-vocals", "Layered duplicate takes"),
    CategorySeed(D.VOCALS, "Autotuned", "autotuned", "Pitch-corrected vocal character"),
    CategorySeed(D.VOCALS, "Vocoder", "vocoder", "Synthesized vocal effect"),
    CategorySeed(D.VOCALS, "Delayed Vocal", "delayed-vocal", "Prominent vocal delay effect"),
    CategorySeed(D.VOCALS, "Layered Vocals", "layered-vocals", "Multiple stacked vocal parts"),
    CategorySeed(D.VOCALS, "Whisper-Pop", "whisper-pop", "Intimate pop whisper aesthetic"),
    CategorySeed(D.VOCALS, "Distorted Vocal", "distorted-vocal", "Saturated or clipped vocal"),
    CategorySeed(D.VOCALS, "Telephone Vocal", "telephone-vocal", "Band-limited phone-filter vocal"),
    CategorySeed(D.VOCALS, "Chorus Vocal", "chorus-vocal", "Modulated chorus effect on vocal"),
    # Non-lexical & special
    CategorySeed(D.VOCALS, "Wordless Vocals", "wordless-vocals", "Vocalizing without lyrics"),
    CategorySeed(D.VOCALS, "Vocalise", "vocalise", "Classical wordless vocal line"),
    CategorySeed(D.VOCALS, "Hum", "hum", "Closed-mouth vocal tone"),
    CategorySeed(D.VOCALS, "Ooh/Aah", "ooh-aah", "Syllabic vowel backing vocals"),
    CategorySeed(D.VOCALS, "Chant", "chant", "Rhythmic repeated vocal phrase"),
    CategorySeed(D.VOCALS, "Narrator", "narrator", "Storytelling spoken narration"),
    CategorySeed(D.VOCALS, "Non-English Vocal", "non-english-vocal", "Lyrics in a non-English language"),
)
